#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

readarray -t kb_conf_lines < /etc/default/keyboard

for idx in "${!kb_conf_lines[@]}"; do
  line="${kb_conf_lines[idx]}"
  if [[ "${line}" =~ ^'XKBLAYOUT=' ]] \
    || [[ "${line}" =~ ^'XKBVARIANT=' ]] \
    || [[ "${line}" =~ ^'XKBOPTIONS=' ]]; then
    unset "kb_conf_lines[${idx}]"
  fi
done

readarray -t new_kb_lines < /dev/shm/fixkb-layout

printf '%s\n' "${kb_conf_lines[@]}" "${new_kb_lines[@]}" > /etc/default/keyboard

setupcon --save-only
dracut --regenerate-all --force
