#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

readarray -t new_kb_lines < /dev/shm/fixkb-layout || true
if [ "${#new_kb_lines[@]}" != '3' ]; then
  printf '%s\n' "$0: ERROR: Absent or corrupt keyboard layout information in '/dev/shm/fixkb-layout'!"
  exit 1
fi

## Use '--no-update-grub' because regenerating the GRUB configuration file is handled elsewhere.
set-system-keymap --no-update-grub "${new_kb_lines[0]}" "${new_kb_lines[1]}" "${new_kb_lines[2]}"

dracut --regenerate-all --force
