#!/bin/bash

## Copyright (C) 2020 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Compare calamares-settings-debian with derivative calamares settings.

set -x

difftool=meld

dir1="/etc/calamares"
dir2="etc/calamares"

# Optional suffix for original files
orig_maybe=".dist"

# Function to compare files
compare_files() {
    local file1="$1"
    local file2="$2"
    $difftool ${file1} "${file2}"
}

# Iterate over the files and directories within the base directory
find "$dir1" -type f | while read -r file; do
    # Construct the corresponding file path in the second directory
    true "file: $file"
    file2=${file/$dir1/$dir2}

    # Check if the corresponding file exists in the second directory
    if [ -f "$file2" ]; then
        compare_files "$file" "$file2${orig_maybe}"
    fi
    if [ -f "$file2${orig_maybe}" ]; then
        compare_files "$file" "$file2${orig_maybe}"
    fi
done

$difftool /usr/bin/add-calamares-desktop-icon usr/bin/add-calamares-desktop-icon.dist
$difftool /usr/bin/install-debian usr/bin/install-host
$difftool /usr/share/applications/install-debian.desktop usr/share/applications/install-host.desktop

true
