#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## /LiOS/squashfs.imgve is a dracut default.
##
## /etc/grub.d/01_live-config-dist will conditionally inject live_config_dist_args
## into GRUB_CMDLINE_LINUX (grub "linux" command).

cat <<EOF
if test -f /LiveOS/squashfs.img; then
  set live_config_dist_args="squashfs_detected root=live:CDLABEL=test rd.live.image rd.debug rd.live.debug rd.live.overlay.overlayfs=1 console=ttyS0"
else
  set live_config_dist_args="no_squashfs_detected"
fi
EOF
